#if !canImport(ObjectiveC)
import XCTest

extension RomanNumeralsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RomanNumeralsTests = [
        ("test_init", test_init),
        ("test_init_string_error", test_init_string_error),
        ("test_init_string", test_init_string),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RomanNumeralsTests.__allTests__RomanNumeralsTests),
    ]
}
#endif
