#if !canImport(ObjectiveC)
import XCTest

extension RomanNumeralsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RomanNumeralsTests = [
        ("test_init", test_init),
        ("test_init_string_error", test_init_string_error),
        ("test_init_string", test_init_string),
        ("test_int_1000", test_int_1000),
        ("test_int_100", test_int_100),
        ("test_int_10", test_int_10),
        ("test_int_1", test_int_1),
        ("test_int_2", test_int_2),
        ("test_int_500", test_int_500),
        ("test_int_50", test_int_50),
        ("test_int_5", test_int_5),
        ("test_int_empty", test_int_empty),
        ("test_string_1000", test_string_1000),
        ("test_string_100", test_string_100),
        ("test_string_10", test_string_10),
        ("test_string_1", test_string_1),
        ("test_string_500", test_string_500),
        ("test_string_50", test_string_50),
        ("test_string_5", test_string_5),
        ("test_string_empty", test_string_empty),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RomanNumeralsTests.__allTests__RomanNumeralsTests),
    ]
}
#endif
